#-------------------------------
# General Site Settings

title: Data Visualisation with Python
description: >- # this means to ignore newlines until "baseurl:" 
  Blog site to fufill the requirements of INTP-315 Emerging Trends
  for the completion of a SAIT ITSD Diploma. This blog will cover 
  the basic fundamentals for utlising data visualisation via python.
domain: "alexhill-sd.github.io"
baseurl: "/Data-Visualsation-with-Python---INTP-315-Blog" # the subpath of your site, e.g. /blog
url: "https://alexhill-sd.github.io" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Alex Hill
author-avatar: profile-min.jpg


#-------------------------------
# Contact links
#facebook:  https://facebook.com/ # Add your Facebook handle
#twitter:   https://twitter.com/ # Add your Facebook handle
#instagram: https://www.instagram.com/ # Add your Facebook handle
#pinterest: https://www.pinterest.com/ # Add your Facebook handle
github: https://github.com/AlexHill-SD # Add your GitHub handle
linkedin: https://www.linkedin.com/in/alexander-hill-87a197a7/ #Add your LinkedIn handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: intp315blog # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
#mailchimp: https://github.us14.list-manage.com/subscribe?u=e92dfc168f585127ac4c6bcf7&amp;id=c0e8dd2916 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

#-------------------------
#Compress HTML - http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: []
  startings: []
  endings: []
  ignore:
    envs: []
  blanklines: false #remove only entirely blank lines
  profile: false #display table at bottom of page to show change in page size

#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
